<template>
  <!-- Generated by IcoMoon.io -->
  <svg
    version="1.1"
    xmlns="http://www.w3.org/2000/svg"
    width="32"
    height="32"
    viewBox="0 0 32 32"
  >
    <title>add-2</title>
    <path
      fill="currentColor"
      d="M28.235 12.19h-8.426v-8.426c0-2.070-1.739-3.765-3.81-3.765s-3.81 1.694-3.81 3.765v8.426h-8.426c-2.070 0-3.765 1.739-3.765 3.81s1.694 3.81 3.765 3.81h8.426v8.426c0 2.070 1.739 3.765 3.81 3.765s3.81-1.694 3.81-3.765v-8.426h8.426c2.070 0 3.765-1.739 3.765-3.81s-1.694-3.81-3.765-3.81z"
    ></path>
  </svg>
</template>
