<template>
  <!-- Generated by IcoMoon.io -->
  <svg
    version="1.1"
    id="Capa_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    viewBox="0 0 1024 1024"
    style="enable-background:new 0 0 1024 1024;"
    xml:space="preserve"
  >
    <path
      fill="currentColor"
      d="M951.6,439.6H584.4V72.4C584.4,32.6,551.8,0,512,0c-39.8,0-72.4,32.6-72.4,72.4v367.1H72.4C32.6,439.6,0,472.2,0,512
	c0,39.8,32.6,72.4,72.4,72.4h367.1v367.1c0,39.8,32.6,72.4,72.4,72.4c39.8,0,72.4-32.6,72.4-72.4V584.4h367.1
	c39.8,0,72.4-32.6,72.4-72.4C1024,472.2,991.4,439.6,951.6,439.6z"
    />
  </svg>
</template>
