<template>
  <!-- Generated by IcoMoon.io -->
  <svg
    version="1.1"
    id="Layer_1"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    x="0px"
    y="0px"
    viewBox="0 0 1024 1024"
    style="enable-background:new 0 0 1024 1024;"
    xml:space="preserve"
  >
    <g>
      <g>
        <path
          fill="currentColor"
          d="M1003.9,156.8c-19.8-19.8-51.9-19.8-71.6,0L325.1,763.9L91.9,530.6c-19.8-19.8-51.9-19.8-71.6,0
			c-19.8,19.8-19.8,51.9,0,71.6l269.2,269.2c19.8,19.8,51.9,19.8,71.6,0l642.9-642.9C1023.7,208.8,1023.6,176.6,1003.9,156.8z"
        />
      </g>
    </g>
  </svg>
</template>
